In [1]:
# make stimuli and subject lists

In [18]:
import os, sys, random
import pandas as pd
import numpy as np


In [19]:
# 5 commercial
# 5 health_neutral
# 5 tailored_match
# 5 tailored_unmatch

commercial_list = [   'commercial_neutral_1',
                      'commercial_neutral_2',
                      'commercial_neutral_3',
                      'commercial_neutral_4',
                      'commercial_neutral_5']

health_neutral_list =['health_neutral_1',
                      'health_neutral_2',
                      'health_neutral_3',
                      'health_neutral_4',
                      'health_neutral_5']


# for each of these, we will have two separate named versions, 
# e.g., matched_unmatched_drunk_driving_A and matched_unmatched_drunk_driving_C for AA and caucasia, respectively
matched_unmatched_list = [ 'matched_unmatched_1',
                      'matched_unmatched_2',
                      'matched_unmatched_3',
                      'matched_unmatched_4',
                      'matched_unmatched_5',
                      'matched_unmatched_6',
                      'matched_unmatched_7',
                      'matched_unmatched_8',
                      'matched_unmatched_9',
                      'matched_unmatched_10']

a_c_list = ['_A', '_C'] *5
a_c_list

#a_c_list_inv = 

#n_billboards = len(health_list)

['_A', '_C', '_A', '_C', '_A', '_C', '_A', '_C', '_A', '_C']

In [21]:
subj_file_names_A = []
for i in list(np.arange(40)+1):
     subj_file_names_A.append('sub' + (str(i).zfill(3)) + '_A_billboards_positions.csv')

subj_file_names_A[:3]

['sub001_A_billboards_positions.csv',
 'sub002_A_billboards_positions.csv',
 'sub003_A_billboards_positions.csv']

In [22]:
subj_file_names_C = []
for i in list(np.arange(40)+1):
     subj_file_names_C.append('sub' + (str(i).zfill(3)) + '_C_billboards_positions.csv')

subj_file_names_C[:3]

['sub001_C_billboards_positions.csv',
 'sub002_C_billboards_positions.csv',
 'sub003_C_billboards_positions.csv']

In [27]:
np.asarray(bb_list)

array([['commercial_neutral_1', 'commercial_neutral_2',
        'commercial_neutral_3', 'commercial_neutral_4',
        'commercial_neutral_5'],
       ['health_neutral_1', 'health_neutral_2', 'health_neutral_3',
        'health_neutral_4', 'health_neutral_5']], dtype='<U20')

In [34]:
curr_m_u

'matched_unmatched_1_A'

In [45]:
for sub_count in range(40):
    
    np.random.shuffle(matched_unmatched_list) #shuffle the m_u_list so that the a/c assignments vary over people
    
    bb_list = []
    bb_list.extend(commercial_list) #always use same commercials
    bb_list.extend(health_neutral_list) #always use same health
    
    for mu_count in range(10):
        curr_m_u = matched_unmatched_list[mu_count] + a_c_list[mu_count]  #combine the shuffled m/u items with the a/c/a/c -- so that there's always 5 mathced, 5 unmatched
        bb_list.append(curr_m_u)
        #print(curr_m_u)
    
    np.random.shuffle(bb_list)  #shuffle the list so that it is all random in terms of sequence ...
    

    #print out one for A
    df = pd.DataFrame()
    df['position'] = np.arange(20)+1
    df['billboard_name'] = bb_list
    df.to_csv('../data/stimuli_subject_filesT/' + subj_file_names_A[sub_count], index=False)
    print(subj_file_names_A[sub_count])
    
    #print out one for C -- same as for A, but the matching/unmatching will be opposite.
    df = pd.DataFrame()
    df['position'] = np.arange(20)+1
    df['billboard_name'] = bb_list
    df.to_csv('../data/stimuli_subject_filesT/' + subj_file_names_C[sub_count], index=False)
    print(subj_file_names_C[sub_count])

sub001_A_billboards_positions.csv
sub001_C_billboards_positions.csv
sub002_A_billboards_positions.csv
sub002_C_billboards_positions.csv
sub003_A_billboards_positions.csv
sub003_C_billboards_positions.csv
sub004_A_billboards_positions.csv
sub004_C_billboards_positions.csv
sub005_A_billboards_positions.csv
sub005_C_billboards_positions.csv
sub006_A_billboards_positions.csv
sub006_C_billboards_positions.csv
sub007_A_billboards_positions.csv
sub007_C_billboards_positions.csv
sub008_A_billboards_positions.csv
sub008_C_billboards_positions.csv
sub009_A_billboards_positions.csv
sub009_C_billboards_positions.csv
sub010_A_billboards_positions.csv
sub010_C_billboards_positions.csv
sub011_A_billboards_positions.csv
sub011_C_billboards_positions.csv
sub012_A_billboards_positions.csv
sub012_C_billboards_positions.csv
sub013_A_billboards_positions.csv
sub013_C_billboards_positions.csv
sub014_A_billboards_positions.csv
sub014_C_billboards_positions.csv
sub015_A_billboards_positions.csv
sub015_C_billb

In [37]:
bb_list

['commercial_neutral_1',
 'commercial_neutral_2',
 'commercial_neutral_3',
 'commercial_neutral_4',
 'commercial_neutral_5',
 'health_neutral_1',
 'health_neutral_2',
 'health_neutral_3',
 'health_neutral_4',
 'health_neutral_5',
 'matched_unmatched_1_A']

In [7]:
# say 40 participants -- everybody gets 20 messages. ...


In [8]:
subj_file_names = []
for i in list(np.arange(40)+1):
     subj_file_names.append('sub' + (str(i).zfill(3)) + '_billboards_positions.csv')

subj_file_names[:3]

['sub001_billboards_positions.csv',
 'sub002_billboards_positions.csv',
 'sub003_billboards_positions.csv']

In [64]:
health_list

['diabetes',
 'smoking',
 'sunscreen',
 'distracted_driving',
 'binge_drinking',
 'underage_drinking',
 'hiv',
 'drugged_driving',
 'buckle_up',
 'vaccination']

In [66]:
sub_count = 0

for current_subj in range(20):
    print('-----')
    print(current_subj)
    print('-----')
    
    sub_count = sub_count +1
    print(sub_count)

    current_list  = []
    current_list_inv = []

    random.shuffle(health_list)
    random.shuffle(commercial_list)

    
    
    for counter in range(n_billboards):
        current_type          = emo_neu_list[counter]
        current_type_inv      = emo_neu_list_inv[counter]
        current_health_bb     = health_list[counter] 
        current_commercial_bb = commercial_list[counter] 
        #print(current_type)
        #print(current_health_bb)
        #print(current_commercial_bb)
    
        current_list.append(current_health_bb     + current_type)
        current_list.append(current_commercial_bb + current_type)
    
        current_list_inv.append(current_health_bb     + current_type_inv)
        current_list_inv.append(current_commercial_bb + current_type_inv)
    
    #complicated/more than it has to be function to sort both lists the same way
    sorting_array = np.arange(20)

    np.random.shuffle(sorting_array)
    print(sorting_array)
    arrayed_current_list = np.asarray(current_list)
    arrayed_current_list_sorted = arrayed_current_list[sorting_array]

    arrayed_current_list_inv = np.asarray(current_list_inv)
    arrayed_current_list_sorted_inv = arrayed_current_list_inv[sorting_array]


    
    
    df = pd.DataFrame()
    df['position'] = np.arange(20)+1
    df['billboard_name'] = arrayed_current_list_sorted
    df.to_csv('../data/stimuli_subject_files/' + subj_file_names[sub_count-1], index=False)
    print(arrayed_current_list_sorted[:1])
    print(subj_file_names[sub_count-1])
        
    print('---')
    sub_count = sub_count +1
    print(sub_count)
    df['billboard_name'] = arrayed_current_list_sorted_inv
    df.to_csv('../data/stimuli_subject_files/' + subj_file_names[sub_count-1], index=False)
    print(arrayed_current_list_sorted_inv[:1])
    print(subj_file_names[sub_count-1])
    
    print('-----')


-----
0
-----
1
[ 4  3  8 10 18 15  5  2 17 19 14  9 13 11 12  0 16  1  7  6]
['buckle_up_emo']
sub001_billboards_positions.csv
---
2
['buckle_up_neu']
sub002_billboards_positions.csv
-----
-----
1
-----
3
[13  6 15 18 10 17 12  8 14  7 19  9  5  1 16 11  4  0  3  2]
['lawyer_emo']
sub003_billboards_positions.csv
---
4
['lawyer_neu']
sub004_billboards_positions.csv
-----
-----
2
-----
5
[13 11  0 17 12 14 10 16 19  4 18  9  3  6 15  1  8  2  7  5]
['smartphone_emo']
sub005_billboards_positions.csv
---
6
['smartphone_neu']
sub006_billboards_positions.csv
-----
-----
3
-----
7
[ 0  8  6 10 15 12 14  7 18  2  4  9 11  3 13  5  1 16 19 17]
['drugged_driving_emo']
sub007_billboards_positions.csv
---
8
['drugged_driving_neu']
sub008_billboards_positions.csv
-----
-----
4
-----
9
[13 14  4 17 15 18 12  7  6 19  1 16  2  0 10  5  8 11  3  9]
['burger_emo']
sub009_billboards_positions.csv
---
10
['burger_neu']
sub010_billboards_positions.csv
-----
-----
5
-----
11
[ 5 17  6  4 18  3  2  9 16  0

In [58]:
df

position             banner_name
0          1           sunscreen_emo
1          2              coffee_neu
2          3  distracted_driving_emo
3          4          smartphone_emo
4          5              brunch_neu
5          6      binge_drinking_emo
6          7           buckle_up_neu
7          8               hotel_emo
8          9              lawyer_neu
9         10                 hiv_neu
10        11           furniture_neu
11        12  education_donation_emo
12        13              burger_emo
13        14               pizza_emo
14        15               salad_neu
15        16   underage_drinking_neu
16        17     drugged_driving_emo
17        18             smoking_emo
18        19         vaccination_neu
19        20            diabetes_neu